### PR TITLE
Python 3.5 compatible string formatting

### PR DESCRIPTION
**Pull request by flycam**
When deploying a flask project implementing pwnedapi on the production server running debian stable (stretch), pwnedapi failed to install via pip. Version 0.3.0 failed, and version 0.4.0 was not available due to minimum python version 3.6. Debian stretch still ships with python 3.5 only. 
Since only string formatting is affected, and there is only one instance in the actual Password class, I decided to add python 3.5 compatibility by replacing f"{}" with "{}".format() rather than messing with the python version on the production servers. Less elegant though, but might help others wanting to use this lib.

### CODE REVIEW

**Comment by nikoheikkila** [comment]
Hi, thanks for the PR!

Normally I'd advise to run your Flask app in a Docker container for keeping Python versions in order. However, since the changes affect only string formatting and Python 3.5 is still maintained I can accept this.

I'll review this more closely. Meanwhile, could you squash the commits and keep the most descriptive commit message, please?

**Comment by flycam** [comment]
I squashed the commits and fixed the formatting as requested, however, would need help with the travis ci. Never used it before.

**Comment by nikoheikkila** [comment]
There were some errors while installing `pycodestyle` so I switched linters. Also Python 3.7 does not work well with Travis as far as I can see (related to OpenSSL availability on Trusty).

You can now try to merge changes from upstream and fix conflicts. In the end you should get a passing build for Python 3.5 and 3.6.

**Comment by nikoheikkila** [comment]
Looking at the latest build result there's this line:

```
setup.py:68:52: E0100 SyntaxError: invalid syntax [pylama]
```

There's [one f-string you missed](https://github.com/flycam/pwnedapi/blob/master/setup.py#L68). Once it gets fixed this should be good to merge as unit tests do pass.

**Comment by nikoheikkila** [comment]
Thanks again for contributing @flycam. I've pushed version 0.5.0 to PyPI so you can test it. Open a new issue / PR if you find anything. 🤛

**Comment by flycam** [comment]
Thanks, I've seen it published.

**Pull request merged**
